### ISSUE TITLE
DS creation failed because too big

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/GMQL#1]
job_testid91_bernasconi_20170322_195107	

DS_CREATION_FAILED	Input Dataset is empty , (error in process or Wrong input Selection query).	

query:
A = SELECT( region: left>1000000 ) HG19_ENCODE_BED;
MATERIALIZE A into outSel;

I realize this is a HUGE output dataset. Nevertheless: is this the correct message of the system in this case?

**Comment by akaitoua** [comment]
@andreagulino @acanakoglu , the problem of writing too many files can be fixed by running on Yarn. But the messaging problem should be fixed @andreagulino.

**Comment by akaitoua** [comment]
Somehow fixed on /gmql-rest-test/, please do test it now @sunbrn

**Comment by marcomass** [comment]
Unfortunately the error still persist ... ;-(

**Comment by akaitoua** [comment]
Fixed.

**Comment by sunbrn** [comment]
@marcomass I confirm this is solved with my initial testing query.
