### ISSUE TITLE
Double MATERIALIZE

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#10]
Fix replicated MATERIALIZE statement issue (at compile or run time).

MATERIALIZE res INTO res;
MATERIALIZE res INTO res;

If the exact same materialize statement is included more than once in a query, compiling is successful but the following runtime error occurs:
2017-03-27 14:18:08,750 ERROR [GMQLSparkExecutor] Output directory hdfs://genomic.elet.polimi.it:9000/user/guest_new44/regions/job_gmql_exam_1_guest_new44_20170327_141635_H3K4me1/exp already exists

**Comment by pp86** [comment]
@marcomass we realised that this error is not so important in the discussion with all

**Comment by marcomass** [comment]
I agree that there are other issues more important that this.
Yet, the problem with this issue is that when in a query two or more MATERIALIZE save results in the same file, a DS_CREATION_FAILED error arises and the query stops without saving any results, which can occur at the end of a long query.
Is it difficult at compile time to keep a list of the names of the mateirialized files and see if any name appears more than once, exactly as it is done with the names of the variables?
