### ISSUE TITLE
JOIN on _attribute output option

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/GMQL#101]
When I use
`RESULT = JOIN(on_attributes: score)  DS1 DS2`
I get this compilation error:

> JOIN operator at line 5: when a condition on distance is not provided, the only possible region builders are LEFT and RIGHT.

Why are other output possibilities precluded? What is the rational behind this? Why don't we allow LEFT_DISTINCT/RIGHT_DISTINCT instead?

Can you help me to understand this @pp86 @akaitoua @OlgaGorlova? Who implemented this choice? Thanks.

**Comment by pp86** [comment]
Option such as CONTIG and INTERSECTION are not possible since the two regions may be on different chr/strands.

I allowed at compile level LEFT_DISTINCT/RIGHT_DISTINCT instead.
The engine should not have problems.

**Comment by marcomass** [comment]
@pp86  
For conformity with the general use of JOIN, I would add also BOTH; do you agree? 

Limiting the control at compiler level requires to implement the same control in any application using the API; wouldn't be better to add the control also at API level?

**Comment by marcomass** [comment]
@pp86 
Please add also BOTH option.

Can the control to prevent using CAT and INT as output options be implemented at API level?

**Comment by marcomass** [comment]
Currently no control is implemented to prevent using CAT and INT with on_attributes option.
This is not what specified in the documentation.
Please implement it.
