### ISSUE TITLE
PROJECT(metadata_update)

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#111]
Surprisingly, it seems that PROJECT(metadata_update) is not able to create a new attribute in a sample of a dataset if that attribute name exists in another sample (not even in the same sample) of the same dataset. 

This case, difficult to describe, is more easily understandable using the here below testing query.
The first SELECT extracts 2 samples, one including the metadata attribute biospecimen_bio_bcr_sample_barcode and the other the metadata attribute biospecimen__bio__bcr_sample_barcode. With the following two PROJECT operations these metadata attributes are copied in an attribute named pippo; yet, only the first PROJECT actually generates the new metadata attribute (in one sample), but the second PROJECT does not produce any metadata attribute (in the other sample). Surprisingly, if the same latter PROJECT is executed to generate a new metadata attribute named pippo1, it actually works correctly!! 

The metadata of the 2 samples in the final ALL_OV_EXPR_DUP dataset should include:
- one sample the two metadata attributes pippo and biospecimen_bio_bcr_sample_barcode 
- one sample the three metadata attributes pippo, pippo1 and biospecimen__bio__bcr_sample_barcode; yet, it includes only pippo1 and biospecimen__bio__bcr_sample_barcode

Testing code:
ALL_OV_EXPR = SELECT(manually_curated__cases__disease_type == "Ovarian Serous Cystadenocarcinoma" AND 
    (biospecimen_bio_bcr_sample_barcode == "TCGA-09-2044-01B" OR
    biospecimen__bio__bcr_sample_barcode == "TCGA-09-2044-01B" OR 
    biospecimen_bio_bcr_sample_barcode == "TCGA-24-0982-01A" OR 
    biospecimen__bio__bcr_sample_barcode == "TCGA-24-0982-01A")) GRCh38_TCGA_gene_expression; 
MATERIALIZE ALL_OV_EXPR INTO ALL_OV_EXPR;

ALL_OV_EXPR_DUP_0 = PROJECT(metadata_update: pippo AS biospecimen_bio_bcr_sample_barcode) ALL_OV_EXPR;
ALL_OV_EXPR_DUP_1 = PROJECT(metadata_update: pippo AS biospecimen__bio__bcr_sample_barcode) ALL_OV_EXPR_DUP_0;
ALL_OV_EXPR_DUP = PROJECT(metadata_update: pippo1 AS biospecimen__bio__bcr_sample_barcode) ALL_OV_EXPR_DUP_1;

MATERIALIZE ALL_OV_EXPR_DUP_0 INTO ALL_OV_EXPR_DUP_0;
MATERIALIZE ALL_OV_EXPR_DUP_1 INTO ALL_OV_EXPR_DUP_1;
MATERIALIZE ALL_OV_EXPR_DUP INTO ALL_OV_EXPR_DUP;

**Comment by pp86** [comment]
This is in contrast with the issue #89 ; in this case you want to produce twice the same attribute-value metadata pair. But, as response of #89 this possibility has been deactivated.

I suggest either to revert #89 or to close this one.

**Comment by marcomass** [comment]
Thank you for mentioning issue #89 , which is useful for better clarification. 
This case is not the same as of issue #89 . 
Here, the result is having in the same sample two different attributes with same vale but different names.
Please note that in the input dataset each sample has only the metadata attribute biospecimen_bio_bcr_sample_barcode or only the metadata attribute biospecimen__bio__bcr_sample_barcode; such two attributes never occur together in the same metadata file.

It seems to me that to cover this case, the check that avoids having duplicate metadata attributes should be done at the single sample level, which now seems not to be the case.

**Comment by acanakoglu** [comment]
I agree with @pp86 these two issues are in conflict. As I explained you directly, we should select one of them.

**Comment by acanakoglu** [comment]
@marcomass , as we discussed it has a conflict, so it was invalid to open this issue.
