### ISSUE TITLE
Profiler - Incorrect counting of samples when some samples do not include regions

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#112]
When a GMQL operation produces a datasets that includes samples without regions, correctly the materialization of such dataset does not generates files (either meta or region) of such samples without regions. Yet, the profiler counts also such "empty" samples, generating an incorrect sample number count; please correct.

**Comment by andreagulino** [comment]
Fixed
@marcomass you can check the result on my account : exusecasemod_20180830_220140_MUTATION_GENE_count
