### ISSUE TITLE
PROJECT - Creation of new metadata based on new or existing metadata

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#16]
PROJECT
Make possible to create new metadata attributes, also based on mathematical expressions on existing metadata attributes [e.g. B = PROJECT(metadata: age_plus AS age + 100) A; or B = PROJECT(metadata_update: age AS age + 100) A; or B = PROJECT(metadata_update: age AS 100) A; or B = PROJECT(metadata: age AS year_from(birthdate)) A;]
o	Implementation: Besides of the required changes, it also requires a careful design

**Comment by pp86** [comment]
@akaitoua also for this I think I need the signature to be defined

**Comment by akaitoua** [comment]
Can not we use a signature similar to extend?

**Comment by pp86** [comment]
We may, but not the same. It has to be defined.

**Comment by akaitoua** [comment]
By looking to the code of the project on Meta data, i found that we already defined and implemented the meta to Meta aggregation. The DAG already take this in account "MetaAggregateStruct". 
 @pp86  would you give it a look. [ProjectMD](https://github.com/DEIB-GECO/GMQL/blob/master/GMQL-Spark/src/main/scala/it/polimi/genomics/spark/implementation/MetaOperators/ProjectMD.scala)

**Comment by pp86** [comment]
Hello, i checked. 

It the MetaAggregateStruct is a metadata aggregator; what it is proposed here is to have a tuple function on metadata.

**Comment by marcomass** [comment]
@pp86 @akaitoua 
So? What should be done to close this issue?

**Comment by pp86** [comment]
First it has to be designed. 
- What kind of operations will be supported
- How is the semantic, i.e., when to cast to numeric, when not to do that
- What if an attribute does not exist or cannot be casted 

Then we will have to include the changes in the DAG, in the compiler and in the engines

**Comment by marcomass** [comment]
@pp86 @akaitoua 
Good to know.
-  What kind of operations will be supported
All aggregation functions already defined, and all basic mathematical operation (+ - * /), including usage of parenthesis (as already done for operations on region attributes, plus possibly sqrt.

- How is the semantic, i.e., when to cast to numeric, when not to do that
Whenever possible, cast to numeric. 

- What if an attribute does not exist or cannot be casted
We already decided that "if the cast fails (i.e. the metadata value is a string not castable) the resulting metadata should contain “GMQL Casting Exception – Could not parse <meta-value>”", or some equivalent lable.

If this above is not enough, can you Pietro make a design proposal and share it?

**Comment by pp86** [comment]
@marcomass 

Why aggregation functions? Isn't this a tuple function?

**Comment by marcomass** [comment]
@pp86 
Yes, you are right.
Let's however suppose you previously did a merge on a dataset. Then, you have all metadata of previous distinct samples within the same single merged sample, with potentially at least some metadata attributes with many values; in this case, being able to aggregate them is useful, don't you think so?

**Comment by akaitoua** [comment]
Dears, since it is easier on you to meet and do the discussion. @pp86, Create the signature for the project command in the DAG and i will do the implementation in the implementation node as soon as you share your branch,

**Comment by akaitoua** [comment]
I rechecked the code, we already have aggregation on Meta in Project that creates new meta attribute from a set of attributes. using a  function we can create new attribute. I think that the work should be done, is from the DAG up to the compiler. To create a mechanism to build the aggregate function from simple math operators like for the extend. This is the definition of the aggregation implemented:
```
trait MetaAggregateStruct extends Serializable{
  val newAttributeName : String
  val inputAttributeNames : List[String]
  val fun : Array[Traversable[String]] => String
}
```
If you see anything else i can do please let me know. I really do not see it now.

**Comment by marcomass** [comment]
@pp86 
The syntax supported is as in the example I initially provided, i.e. as follows?
D1 = PROJECT(metadata_update: age AS 100) D; 
D2 = PROJECT(metadata_update: age AS age + 100) D1; 
D3 = PROJECT(metadata: age_plus AS age + 100) D; 
D4 = PROJECT(metadata: age AS year_from(birthdate))

**Comment by pp86** [comment]
@marcomass 
It is, with the key word "metadata_update" (the last two have only "metadata").

Of course D4 will not work since the year_from function has no definition

**Comment by marcomass** [comment]
@pp86 @akaitoua 
I executed the following query:
D = SELECT() HG19_BED_ANNOTATION;
D1 = PROJECT(metadata_update: age AS 100) D; 
MATERIALIZE D1 INTO D1;
D2 = PROJECT(metadata_update: age AS age + 100) D1; 
MATERIALIZE D2 INTO D2;
D3 = PROJECT(metadata_update: age_plus AS age + 100) D; 
MATERIALIZE D3 INTO D3;
It compiles, but there are no changes in the generated metadata. Can you check?

**Comment by akaitoua** [comment]
@marcomass, Your input data set does not have an attribute called "age" so D3 will not give you anything. 
D1 adds new attribute to the metadata called "age" with the value 100. I am not sure that this is implemented.
D2 is based on D1 so there is no result.

**Comment by marcomass** [comment]
@akaitoua Yes, the purpose of this issue was also to enable creation of new metadata attributes (as age in D1 or age_plus in D3).
If this is not implemented, can you add it? If it depends on compiler, can you add request to Pietro?
Thanks.

**Comment by akaitoua** [comment]
@marcomass I checked this one, i think that there is a problem in the compiler in this section (D1 adds new attribute to the metadata called "age" with the value 100), it is implemented but have some issue (i did not dig more).

**Comment by marcomass** [comment]
@akaitoua @pp86 
Ok, so this (i.e., D1 = PROJECT(metadata_update: age AS 100) D;) should be addressed by Pietro

**Comment by marcomass** [comment]
Creation of a new metadata attribute base on a constant value should be enable for any possible values, i.e., numeric, also negative, or textual (in this case, if any character is not allowed, please specify); examples: 
D1 = PROJECT(metadata_update: age AS 100) D;
D1 = PROJECT(metadata_update: weight AS 100.80) D;
D1 = PROJECT(metadata_update: weight_diff AS -5) D;
D1 = PROJECT(metadata_update: weight_diff AS -0.2) D;
D1 = PROJECT(metadata_update: status AS 'good bye') D;

**Comment by marcomass** [comment]
@pp86 @akaitoua 
Unfortunately I need to reopen this issue since the cases in the above comment are not covered yet in the updated version available on web interface (i.e. no metadata age, weight, weight_diff, status are created at all in output).

Please check it; here below I provide the entire query to test it:
DATA = SELECT(cell == "Urothelia" AND ID == "40") HG19_ENCODE_NARROW;
D = PROJECT(metadata_update: _pippo AS 3 ) DATA;
D1 = PROJECT(metadata_update: age AS 100) D;
D2 = PROJECT(metadata_update: weight AS 100.80) D1;
D3 = PROJECT(metadata_update: weight_diff AS -5) D2;
D4 = PROJECT(metadata_update: weight_diff2 AS -0.2) D3;
D5 = PROJECT(metadata_update: status AS 'good bye') D4;
MATERIALIZE D5 into D5;

**Comment by pp86** [comment]
It looks to me that from the compiler point of view it is working.

I'm going to remove my assignment to this issue, but feel free to add me back if the problem is also in the compiler.

**Comment by marcomass** [comment]
@pp86 
Unfortunately I have to reopen this issue for only the following remaining small aspect at compiler level: 

- when a new metadata attribute is created with constant text value, also the "" containing the value are added as attribute value, but they should not (i.e., the following query should create a metadata status with value good bye; now its value is created as "good bye")
DATA = SELECT(cell == "Urothelia" AND ID == "40") HG19_ENCODE_NARROW;
D5 = PROJECT(metadata_update: status AS "good bye") DATA;
MATERIALIZE D5 into D5;

**Comment by marcomass** [comment]
@pp86
The above aspect to be fixed apply also to region attributes, i.e., when a new region attribute is created with constant text value, the "" containing the value should not be added as attribute value, i.e., the following query should create a region attribute named mystring with value pippo and another attribute mystring2 with value empty string (now the two attributes are created, but with value "pippo" and "", respectively): 
S = SELECT(annotation_type == "promoter") HG19_BED_ANNOTATION;
S0 = PROJECT(region_update: mystring AS "pippo", mystring2 AS "") S; 
MATERIALIZE S0 INTO S0;

**Comment by marcomass** [comment]
@pp86
The issue about the region attribute has been fixed, but the same one regarding the metadata attribute (as described in the above comment) not yet. I need to reopen this issue.

When a new metadata attribute is created with constant text value, do not save as the attribute value the "" (or '') containing the value expressed in the query; i.e., the following query should create a metadata status and a metadata status2, both with value good bye (not "good bye" or 'good bye')
    DATA = SELECT(cell == "Urothelia" AND ID == "40") HG19_ENCODE_NARROW;
    D5 = PROJECT(metadata_update: status AS "good bye") DATA;
    D6 = PROJECT(metadata_update: status2 AS 'good bye') D5;
    MATERIALIZE D6 into D6;

**Comment by marcomass** [comment]
@pp86 
The issue is fixed now, but it must be avoid to assign empty string value to a metadata attribute, since in the model we defined that when a metadata attribute has empty value, the attribute is removed from the metadata.
So, instructions:  
- metadata_update: _empty AS "" 
- metadata_update: _empty2 AS '' 
must be not acceptable.
I reopen the issue just for this small fixing.
