### ISSUE TITLE
COVER - mathematical expressions with the ALL keyword

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#18]
COVER / SUMMIT / FLAT / HISTOGRAM:
Support using mathematical expressions with the ALL keyword as accumulation values for COVER [e.g. B = COVER(1, ALL/2) A;] 
o	Implementation: requires changes at all the levels

**Comment by akaitoua** [comment]
@pp86 is this modification implemented in the compiler?

**Comment by pp86** [comment]
@akaitoua sorry, I did notice this question. By the way it is not included in the compiler

**Comment by pp86** [comment]
@akaitoua please, let me know exactly what kind of expression is expected by the low level and I will include it in the compiler

**Comment by pp86** [comment]
Hello @akaitoua , I need the signature in order to do that.

**Comment by akaitoua** [comment]
I will provide it tonight

**Comment by akaitoua** [comment]
@pp86, I did the changes to get a function on the ALL and ANY parameters in COVER. @pp86 please check the new branch named CoverParameters and especially the [last commit](https://github.com/DEIB-GECO/GMQL/commit/7b321250099998e04fe82edb5d770dc20a26bade) on the new branch called "Flink executed from compiler" (I mistakenly left an old message for this commit).

**Comment by pp86** [comment]
Hello @akaitoua ,

it is not very clear to me. Take for example the case ANY/2. What should I pass to the lower layer?

**Comment by akaitoua** [comment]
@pp86, This is an example on how to call the DAG. 
DS1.COVER(CoverFlag.COVER, new N{override val n=2}, new ALL{
      override val fun: (Int) => Int = (x)=>x/2}, List(), None )

This is equivalent to : COVER(2,ALL/2)
Please check the changes that i introduced on the compiler in the link above.

**Comment by akaitoua** [comment]
@pp86, if you agree i will merge the branch with the master branch. I tested it and it is working.

**Comment by marcomass** [comment]
@akaitoua @pp86 Is this ready?

**Comment by marcomass** [comment]
@akaitoua @pp86 Hi. I think we need to have this implemented as floor(ALL/k) so that when k=2,, with (ALL+1)/k we always have an integer number above or equal ALL/2 (based on ALL is even or odd); do you agree?

**Comment by pp86** [comment]
@akaitoua Hello, yes please merge. I forgot to ask before doing the changes XD

**Comment by akaitoua** [comment]
@pp86, I did the merge and tried to test. The compiler still does not recognise the division. 

Error: Operator COVER at line 2: invalid unnamed parameter 2 , ALL / 2

**Comment by pp86** [comment]
@akaitoua yes, I did not commit since it was not compiling.
I'll do it now. tnx btw!

**Comment by pp86** [comment]
@akaitoua Ok, looks like it is working now, thanks for the support again.

**Comment by pp86** [comment]
@marcomass about your comment, i made it supports these two kind of expressions:

- ALL / k
- (ALL + n) /k

**Comment by marcomass** [comment]
@pp86 @akaitoua 
Ok, thanks.
How is it implemented the casting / approximation of the division to the integer value required by the minAcc maxAcc parameters? As floor(ALL/k)?

**Comment by pp86** [comment]
@marcomass , yes, it is the floor

**Comment by marcomass** [comment]
@pp86 @akaitoua 
Quanto implementato (ALL / k  o (ALL + n) /k) è disponibile anche a livello di API?
Se si, è documentato?

**Comment by akaitoua** [comment]
Ok. I will add the documentation.

Sent from my iPhone

On 30 May 2017, at 00:49, marcomass <notifications@github.com<mailto:notifications@github.com>> wrote:


@pp86<https://github.com/pp86> @akaitoua<https://github.com/akaitoua>
Quanto implementato (ALL / k o (ALL + n) /k) è disponibile anche a livello di API?
Se si, è documentato?

**Comment by Erlaad** [comment]
[issue18.zip](https://github.com/DEIB-GECO/GMQL/files/1284126/issue18.zip)
Tested and confirmed. See attached query.

**Comment by marcomass** [comment]
Tested by Stefano P (Erlaad) with the following query:
DATA = SELECT(biosample_term_name == "K562" AND experiment_target == "ATF3-human") HG19_ENCODE_NARROW_NOV_2016;
MATERIALIZE DATA into data; # Includes 3 samples
RESULT = COVER(1,ALL/2) DATA; # Expected result of ALL/2: 1
MATERIALIZE RESULT into res;
RESULT2 = COVER(1,(ALL+1)/2) DATA; # Expected result of (ALL+1)/2: 2
MATERIALIZE RESULT2 into res2;
RESULT3 = COVER(1,(ALL+11)/2) DATA; # Expected result of (ALL+11)/2: 7 (but max is 3)
MATERIALIZE RESULT3 into res3;
#RESULT4 = COVER(1,(ALL-1)/2) DATA; # Expected result of (ALL-1)/2: 1 (error) ## unfortunately ALL-k not supported ...
#MATERIALIZE RESULT4 into res4;
