### ISSUE TITLE
Dataset content statistics 

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#19]
Provide descriptive statistics at dataset level (e.g. number of samples, number of regions, ...) [these can be included in an additional file within the dateset zip file]

**Comment by andreagulino** [comment]
@marcomass implemented

**Comment by marcomass** [comment]
Very good!
Just a couple of small fixes: 
@acanakoglu 
Please Arif, in the visualization window in the UI can you change "Key" to "Attribute" 

@andreagulino, @acanakoglu 
Can you please set the value of the attribute "Number of regions" to be visualized as integer?

**Comment by andreagulino** [comment]
> Can you please set the value of the attribute "Number of regions" to be visualized as integer? <

@marcomass  fixed with  [this commit](https://github.com/DEIB-GECO/GMQL/commit/1140a383c952dc638f93a296789b3cbe165f01e0), it will apply to new datasets, I will re-profile the old ones to fix old profiles

**Comment by marcomass** [comment]
Ok.
@acanakoglu 
In the same info window, please change "Sample Profile not available" to "Sample profile not available" (when applied to a sample with no profile)

**Comment by marcomass** [comment]
@andreagulino 
Please change text as follow (avoiding second word capital for consistency with other attribute names):
- Created By -> Created by 
- Creation Date -> Creation date

@andreagulino @acanakoglu 
Please also provide all the same information/statistics within a file in the downloaded dataset

**Comment by andreagulino** [comment]
@marcomass @acanakoglu 
Fixed "Sample Profile not available", "Created By", "Creation Date" in [this commit](https://github.com/DEIB-GECO/GMQL/commit/df9d0695af5a5436e0aa7b204dc6d28c68f177f2)

@acanakoglu 
not fixed: "Key" to "Attribute"

**Comment by acanakoglu** [comment]
Done

**Comment by marcomass** [comment]
@andreagulino @acanakoglu
Please also provide all the same information/statistics within a file in the downloaded dataset

**Comment by acanakoglu** [comment]
it is added on both side.
