### ISSUE TITLE
Documentation for GMQL package

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#20]
1) Update in stackedit source the typos fixing to GMQL package documentation I wrongly did directly in github.

2) Fix small aspects of documentation as specified in email 

3) Enable automatic connection between stackedit and github

**Comment by akaitoua** [comment]
Automatic connection of stackedit is not working on organization Github. It is a bug in StackEdit.

**Comment by marcomass** [comment]
So, how will be updated the documentation in Github (probably the one the users will look at)?

**Comment by akaitoua** [comment]
by expoting the documentation from editstack on hard disk then replacing the file.

**Comment by marcomass** [comment]
ok, let us know when you have done the updating from editstack in Github

**Comment by akaitoua** [comment]
Documentation installation error is fixed. @acanakoglu Please proceed in checking the installation documentation.
