### ISSUE TITLE
Documentation GMQL API

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#21]
In https://github.com/DEIB-GECO/GMQL/blob/master/docs/GMQL_APIs.md
complete examples of the remaining 7 GMQL commands, so to cover completely all GMQL commands besides the 4 (select, join, cover and map) currently described.

**Comment by akaitoua** [comment]
Examples are added.

**Comment by marcomass** [comment]
Good. If I'm not wrong, one example about EXTEND is still missing; can you add it?

**Comment by akaitoua** [comment]
Added Extend
