### ISSUE TITLE
JOIN - in particular circumstances, replication of factor x4 for all the regions in the result 

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#24]
In particular circumstances, we observe each region in the result of a JOIN incorrectly replicated 4 times.
Please see the attached report for a complete description of the fenomenon. 

[bug report.pdf](https://github.com/DEIB-GECO/GMQL/files/907412/bug.report.pdf)

**Comment by akaitoua** [comment]
fixed in commit 9e3d02b

**Comment by marcomass** [comment]
Very good, now it is fine.
@akaitoua What was causing the issue?
