### ISSUE TITLE
PROJECT - wildchars

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#25]
The new wildchar syntax to specify region attributes in PROJECT is only partially recognized by the compiler.

The following compile:
 D = PROJECT(?.score) C_2;
 E = PROJECT(?.score, ?.name) C_2;

But the following do not compile:
F = PROJECT(DS.?) C_2;
G = PROJECT(my.?.score) C_2;

Here the entire testing query:
 DS = SELECT(ID == '1012') HG19_ENCODE_NARROW;
PROM = SELECT(annotation_type == 'promoter') HG19_BED_ANNOTATION;
C_0 = JOIN() PROM DS;
C_2 = PROJECT(region_update: score AS 99999, my.one.score AS 11111) C_0;
MATERIALIZE C_2 INTO C_2;
 C = PROJECT(score) C_2;
 D = PROJECT(?.score) C_2;
 E = PROJECT(?.score, ?.name) C_2;
 F = PROJECT(DS.?) C_2;
 G = PROJECT(my.?.score) C_2;
MATERIALIZE C INTO C;
MATERIALIZE D INTO D;
MATERIALIZE E INTO E;
MATERIALIZE F INTO F;
MATERIALIZE G INTO G;

**Comment by pp86** [comment]
@marcomass 

Should be fixed now, the example query compiles
