### ISSUE TITLE
groupby / joinby attribute names without prefixes

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#29]
For the groupby and joinby option of all operators make possible to express only the suffix part of a (metadata or region) attribute name.

It was working (I tested it), but now it is not, at least for MERGE.
Please revise and fix it.

**Comment by OlgaGorlova** [comment]
Hello @marcomass ,
I think this was not implemented yet on metadata for groupby.
May I ask you for an example query that you used?

**Comment by marcomass** [comment]
Hi @OlgaGorlova 
An example is the following (on merge, but equal examples could be for other operators):
S2 = MERGE(groupby: biosample_term_name, TF_DNAse.TF.experiment_target) S1;
In this case the groupby applies only on samples with TF_DNAse.TF..experiment_target; if 
S2 = MERGE(groupby: biosample_term_name, experiment_target) S1;
the groupby now applies only on samples with experiment_target, but it should apply on all samples with  metadata attribute ending with .experiment_target having whatever dot prefixes (TF..experiment_target, TF_DNAse.TF..experiment_target, ...) as done for the select joinby

**Comment by marcomass** [comment]
Hi @OlgaGorlova
Could you fix this?
