### ISSUE TITLE
Problem with project "-" operator

### ISSUE THREAD

**Issue by pp86** [DEIB-GECO/GMQL#3]
In PROJECT, arithmetic "-" is not correctly managed with respect to subsequent operands with/without presence of parenthesis; e.g. score1 AS (score)-(score-3)+(4) returns -1 instead of +7; also score2 AS score+5-score-4 returns incorrect result
A = SELECT(cell == 'K562' AND antibody == 'c-Jun' AND ID == '1217') HG19_ENCODE_BED;
B=PROJECT(region_update: score1 AS (score)-(score-3)+(4), score2 AS score+5-score-4) A;
#MATERIALIZE A INTO DatasetTab2;
MATERIALIZE B INTO ProjectedDatasetTab2;

**Comment by pp86** [comment]
@OlgaGorlova 

Please check the code about RESUB and READD within 

GMQL/GMQL-Server/src/main/scala/it/polimi/genomics/GMQLServer/DefaultRegionExtensionFactory.scala

From the history I am the one who committed the changes, but that commit happened just after the big mess with the repository. 
Is it this part of the code you wrote for the START/STOP modification within the PROJECT? (it looks like that) or did I do that?

If so, the strand has to be kept into account only when we are accessing the LEFT/RIGHT attributes.

**Comment by OlgaGorlova** [comment]
Hi @pp86 . Yes, I did change it. I will check it and fix.
