### ISSUE TITLE
ReadMEMMD does not exist in GMQLSparkExecutor

### ISSUE THREAD

**Issue by lucananni93** [DEIB-GECO/GMQL#30]
With the new commit ( https://github.com/DEIB-GECO/GMQL/commit/619f1c051ee75253121e2fcf20402263279212c2?diff=split ) done by @akaitoua the code does not compile.

This is due to the fact that the class _it.polimi.genomics.spark.implementation.RegionsOperators.SelectRegions.**ReadMEMRD**_ does not exist, but it is instantiated anyway in the code of _GMQLSparkExecutor_.

**Comment by akaitoua** [comment]
Fixed

Sent from my iPhone

On 22 May 2017, at 16:00, Luca Nanni <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #30<https://github.com/DEIB-GECO/GMQL/issues/30> to @akaitoua<https://github.com/akaitoua>.
