### ISSUE TITLE
DAG serialization & web service for remote dag execution 

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#33]
Provide in the API the functionality to send a DAG for its execution on a remote machine by web services

**Comment by marcomass** [comment]
@lucananni93 @akaitoua  @andreagulino @acanakoglu 
Hi, what's the status of this urgent issue?

**Comment by lucananni93** [comment]
I have worked with @acanakoglu on this issue and it is going to be released in a TRIAL version this week. We are still encountering some problems with the logging and we have asked @akaitoua to help us on this.

**Comment by lucananni93** [comment]
The service should be working at [this link](http://genomic.elet.polimi.it/gmql-rest-test-dag/). In particular the REST service works with the following syntax: `/queries/dag/{output}` and the serialized DAG is put in the body of the POST request. Check the SWAGGER documentation for further information

**Comment by akaitoua** [comment]
@lucananni93 , @acanakoglu , I did not have the time to fix the logging problem. @acanakoglu we discussed the possible solution for the logging problem. Would you try to fix the logging problem or describe it to @lucananni93.
This message is written based on @marcomass suggestion.

**Comment by lucananni93** [comment]
Dag serialization is up and running on [genomic REST-test](http://genomic.elet.polimi.it/gmql-rest-test).
Please try it.

Luca

**Comment by marcomass** [comment]
In the renaming phase of the dataset (when deciding which name to use for a given input dataset, whether local or remote) the node search does not pass through the select semi-join node, causing an exception.
