### ISSUE TITLE
Fix calculation of AVERAGE when null values are present 

### ISSUE THREAD

**Issue by OlgaGorlova** [DEIB-GECO/GMQL#35]
When there are null values, the AVERAGE function gives a wrong result - it uses count of all values including nulls. Instead, it should count only values without nulls.

**Comment by marcomass** [comment]
@OlgaGorlova 
Good catch. Does this apply only on AVERAGE or also on other aggregation functions? Did you test all of them (MIN, MAX, MEDIAN, STD, BAG, ...)?

**Comment by OlgaGorlova** [comment]
@marcomass, should be only on AVERAGE

**Comment by marcomass** [comment]
@OlgaGorlova Does it mean that you tested all the other aggregation functions and they work correctly also in presence of nulls?

**Comment by OlgaGorlova** [comment]
@marcomass Yes, I tested them and they are working ok, but I did it on a small synthetic data.

**Comment by Erlaad** [comment]
Isn't this a partial duplicate of issue #14 ? If so, I tested and found it working (and reported on related issue).
