### ISSUE TITLE
EXACT, FULLNAME, DEFAULT also in API of COVER and MERGE

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#39]
In the API the possibility to use EXACT, FULLNAME, DEFAULT modifiers for metadata attribute names is present only for the semijoin in the SELECT, and joinby in DIFFERENCE, JOIN and MAP, but not for the groupby in COVER and MERGE.
Add the use of EXACT, FULLNAME, DEFAULT modifiers also to COVER and MERGE in the API

**Comment by OlgaGorlova** [comment]
@pp86 , can you please provide the functionality from the compiler side like you did for joinby?

**Comment by marcomass** [comment]
@pp86 
Please Pietro answer to Olya request, so she can proceed

**Comment by pp86** [comment]
@OlgaGorlova as we did last time, since it was not gonna compile I pushed it to a new branch (https://github.com/DEIB-GECO/GMQL/tree/merge_cover_groupby) .

@lucananni93 I think that some changes will also be required from your side

nb: I'll remove my assignment, please add me back if needed :)

**Comment by OlgaGorlova** [comment]
@pp86 I pushed my changes to https://github.com/DEIB-GECO/GMQL/tree/merge_cover_groupby
It still cannot be compiled, changes from compiler side are needed. I will assign you back.

**Comment by pp86** [comment]
@OlgaGorlova thanks, I'll give a look.

**Comment by pp86** [comment]
@OlgaGorlova I fixed the compilation problem in the Compiler package and merged the branch into the master.

Now there will be problems in compiling the R,Python and SciDB packages (which can be disabled from the pom file in order to build the web application).

**Comment by Sim1Pall8a** [comment]
already fixed

**Comment by lucananni93** [comment]
fixed
