### ISSUE TITLE
Metadata values with quotation mark

### ISSUE THREAD

**Issue by acanakoglu** [DEIB-GECO/GMQL#43]
Double(or single) quotation mark between the double(or single) quotation needs to be escaped by compiler. This could be applied to other string literal fields.

**Comment by pp86** [comment]
Ok, Could you provide an example?

Doesn't:
 

- " ' "
- ' " '

work?

**Comment by acanakoglu** [comment]
Yes, this could resolve the problem however in the case of both type of quotation marks available as value?
In HG19_ENCODE_BED public dataset, there are samples with cell_description with both quotation mark. As an example:

B lymphocyte, "The Raji line of lymphoblast-like cells was established by R.J.V. Pulvertaft in 1963 from a Burkitt's lymphoma of the left maxilla of an 11-year-old Black male." - ATCC. (PMID: 14086209)

**Comment by acanakoglu** [comment]
it is not correct yet.

**Comment by marcomass** [comment]
@acanakoglu 
Still not working completely. In the following case:
DATA_SET_VAR = SELECT(cell_description == "B lymphocyte, \"The Raji line of lymphoblast-like cells was established by R.J.V. Pulvertaft in 1963 from a Burkitt's lymphoma of the left maxilla of an 11-year-old Black male." - ATCC. (PMID: 14086209)") HG19_ENCODE_NARROW;
escape \ should be added also in the second " contained in the value of the attribute cell_description

**Comment by pp86** [comment]
@marcomass 

Could you report the query as you had written?

**Comment by marcomass** [comment]
@pp86 Sorry, I do not understand. The query is just the select I wrote plus its materialize
DATA_SET_VAR = SELECT(cell_description == "B lymphocyte, \"The Raji line of lymphoblast-like cells was established by R.J.V. Pulvertaft in 1963 from a Burkitt's lymphoma of the left maxilla of an 11-year-old Black male." - ATCC. (PMID: 14086209)") HG19_ENCODE_NARROW;
materialize DATA_SET_VAR INTO DATA_SET_VAR;
Possibly the issue depend on adding the escape\ also to the second " contained as value of the attribute; should this be done by Arif?  @acanakoglu

**Comment by acanakoglu** [comment]
This is a problem of GMQL-WEB. I am opening issue again under GMQL-WEB project.
The selection query should be like the below:
DATA_SET_VAR = SELECT(cell_description == "B lymphocyte, \\"The Raji line of lymphoblast-like cells was established by R.J.V. Pulvertaft in 1963 from a Burkitt's lymphoma of the left maxilla of an 11-year-old Black male.\\" - ATCC. (PMID: 14086209)") HG19_ENCODE_NARROW;

@pp86 :
I check on the server, and compilation and execution is working properly
