### ISSUE TITLE
MetaExtension in PROJECT incompatibility

### ISSUE THREAD

**Issue by lucananni93** [DEIB-GECO/GMQL#46]
The new implementation of metadata update in PROJECT through the introduction of `MetaExtension` lacks the following features:

- Add to `it.polimi.genomics.GMQLServer.Implementation` the `MetaExtensionFactory` with the relative Default factory
- The method `get` of `it.polimi.genomics.core.DataStructures.Builtin.MetaExtensionFactory` returns a `MetaAggregateStruct` while the PROJECT operation in  `it.polimi.genomics.core.DataStructures.IRVariable` accepts a `Option[MetaExtension]` which is a subclass of `MetaAggregateStruct`. This must be changed because it makes the `MetaExtensionFactory` useless...

Please, tell me if I am wrong.

Thank you!

**Comment by akaitoua** [comment]
@lucananni93 , can you fix it and close this issue.
