### ISSUE TITLE
ALLBUT for metadata

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#49]
Enable use of ALLBUT also for metadata, also applied to more metadata attributes [e.g. B = PROJECT(metadata: ALLBUT ID, cell, cell_color, cell_sex, lab) A;]. 
Enable also the use of wildchars (e.g., *) to express which set of metadata attributes should be removed [e.g. B = PROJECT(metadata: ALLBUT *.cell, lab_*) A; or B = PROJECT(metadata: setA.*, cell_*) A;]

**Comment by akaitoua** [comment]
Fixed. Now Meta operation has All_But for project. 

I did not consider any wildchars because it will become complex. The only case i considered is the ending with an attribute or start with the attribute.

For example:  ``` B = PROJECT(metadata: ALLBUT cell) A;```  will consider sample.cell and cell.type as cell

**Comment by marcomass** [comment]
@akaitoua 
Good. Yet, both ending with an attribute or start with the attribute could create issues. It is better to use the same rule rule as for the ALLBUT on region data, and enable also for this case the possibility to use attribute modifiers (EXACT, FULLNAME, DEFAULT, ..).

Thus, I reopen the issue, also since the compiler does not recognize the "metadata: ALLBUT cell" syntax.
