### ISSUE TITLE
PROJECT metadata_update compiler bug

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#59]
In PROJECT metadata_update, multiple operations specified are not recognized (only single one). 
Please fix, making it possible to specify multiple operations with the same logic as for region_update.
Test example: 
DATA = SELECT(cell == "Urothelia" AND ID == "40") HG19_ENCODE_NARROW;
RES = PROJECT(metadata_update: _id1 AS ID + 3, _id2 AS ID - 3 ) DATA;
MATERIALIZE RES into res;

**Comment by pp86** [comment]
@OlgaGorlova 
this functionality is not enabled at engine level for the time being (most probably is a very easy one, just needed to iterate over all the received modifiers).

I committed the related compiler changes in the following branch:
https://github.com/DEIB-GECO/GMQL/compare/multiple_metadata_update_issue59

I am removing my assignment, please add me back if my help is needed.
