### ISSUE TITLE
Issues updating from previous github project version

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#6]
Import here the issues (not solved) present in the previus github project version @akaitoua

**Comment by akaitoua** [comment]
Done @marcomass

**Comment by marcomass** [comment]
Actually not yet done. 
In previous version there aretwo open issues that I do not see yet here
- check the data type at compile time
- summit problem

**Comment by akaitoua** [comment]
@marcomass , Submit problem is marked as solved, as Perna mentioned for Andrea. While the other issue is added.
