### ISSUE TITLE
PROJECT metadata_update compiler bug 2

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#60]
Bug in PROJECT metadata_update whit ration between two metadata attributes: the calculated ratio seams to be the inverse of what it should be; this does not occur when the ratio is between a metadata attribute and a constant value. 

Example query: 
DATA = SELECT(cell == "Urothelia" AND ID == "40") HG19_ENCODE_NARROW;
RES = PROJECT(metadata_update: _id2 AS ID*3 ) DATA;
RES_2 = PROJECT(metadata_update: _id3 AS _id2/ID) RES;
MATERIALIZE RES_2 into res;

_id3 results 0.33 instead of 3 (0.5 instead of 2 if _id2 AS ID*2). 

Conversely, when instead of ID I use its numerical value, e.g., 40, the result is correct:
RES_2 = PROJECT(metadata_update: _id3 AS _id2/40) RES;

**Comment by akaitoua** [comment]
@OlgaGorlova, can you check it out.

**Comment by marcomass** [comment]
@OlgaGorlova 
Hi Olya, can you fix this?
