### ISSUE TITLE
PyAPI compatibility

### ISSUE THREAD

**Issue by akaitoua** [DEIB-GECO/GMQL#64]
def project(index: Int, projected_meta : Option[java.util.List[String]],
              extended_meta : Option[MetaExtension],
              all_but_meta: Boolean,
              projected_regs : Option[java.util.List[String]],
              all_but_regs : Option[java.util.List[String]],
              extended_regs : Option[java.util.List[RegionFunction]]
             )

The API changed to:
  extended_meta : Option[List[MetaExtension]]

Would you include the changes in PythonAPI

**Comment by lucananni93** [comment]
No problem. I'll fix it asap

**Comment by Sim1Pall8a** [comment]
already fixed
