### ISSUE TITLE
Distinct BAG

### ISSUE THREAD

**Issue by acanakoglu** [DEIB-GECO/GMQL#66]
In some cases (e.g., when BAG is used in MAP), it would be useful to have all values reported by BAG, not only the distinct ones (which is useful in other cases, e.g., when BAG is used in EXTEND).
Could you provide two versions of bag, exactly with the same functionality, but one named BAGD returning distinct values, and another named BAG returning all values?

**Comment by akaitoua** [comment]
BAGD support is added from the implementation. Notice that BAG implementation is the normal bag that sorts the items but does not perform distinct. 
Compiler support for BAGD is needed. @pp86

**Comment by pp86** [comment]
What the compiler does is just to pass the function identifier dow to the implementation. Once the function is implemented there, it is enough.
