### ISSUE TITLE
Adjacent 

### ISSUE THREAD

**Issue by eirinistam** [DEIB-GECO/GMQL#69]
We want  the distance from the regions to be equal to 0, to have this result we select DGE(0), DLE(0), but the result of the query is empty (I enclose the query and the input datasets.)

query: 
DS1= SELECT()adj_1;
DS2= SELECT()adj_2;
RES = JOIN(DGE(0), DLE(0); output:RIGHT) DS1 DS2;
Inputs:
https://www.dropbox.com/sh/td5txmqmb8vhsc9/AAAJdIZ4o32jYU_rsyfdBEw5a?dl=0

**Comment by andreagulino** [comment]
Looking at the implementation, DGE and DLE are actually implemented as > and <, 
so to get distance = 0, as a temporary solution, you could use DGE(-1), DLE(1).

Let me know if it works, so to confirm what I said
I will then change the implementation

@eirinistam @marcomass 

as a side node, this is the line of code that implements the check on distance

val intersect_distance =
(!firstRoundParameters.max.isDefined || firstRoundParameters.max.get > distance) && (!firstRoundParameters.min.isDefined || firstRoundParameters.min.get < distance)

**Comment by eirinistam** [comment]
With DGE(-1), DLE(1) I have compiled error.
@andreagulino @marcomass

**Comment by marcomass** [comment]
@andreagulino 
The distal conditions described in the documentation are the following:
- MD(K) (or MINDIST(K), MINDISTANCE(K))
- DLE(N) (or DIST <= N, DISTANCE <= N), with any integer value of N 
- DGE(N) (or DIST >= N, DISTANCE >= N), with only values N >= 0 permitted
- DIST < N, DISTANCE < N, with any integer value of N 
- DIST > N, DISTANCE > N, with only values N >= 0 permitted
Please, verify that all these are implemented correctly.
Check also that the cases with negative N values (e.g., DLE(-2)) provide the correct results according to the value of N.

@pp86 
Please, add at compiler level also the following cases:
- DL(N), acting as DIST < N, and DISTANCE < N
- DG(N), acting as DIST > N, and DISTANCE > N

**Comment by andreagulino** [comment]
@marcomass 
@pp86 you could just change the compiler so that the instantiated AtomicCondition(s) are like this:
DL(n)   or DIST <n     -> DistLess(**n**)
DLE(n) or DIST <=n   -> DistLess(**n+1**)
DG(n)   or DIST > n    -> DistGreater(**n**)
DGE(n) or DIST >= n  -> DistGreater(**n-1**)

and the issue can be closed

**Comment by pp86** [comment]
I Implemented the option proposed by @andreagulino in the last message.

**Comment by marcomass** [comment]
@lucananni93 @Sim1Pall8a 
Please update accordingly the Python library and R package

**Comment by Sim1Pall8a** [comment]
already fixed

**Comment by lucananni93** [comment]
fixed
