### ISSUE TITLE
check the data type at compile time

### ISSUE THREAD

**Issue by akaitoua** [DEIB-GECO/GMQL#7]
The following statement:
DATA_SET_VAR = SELECT(region: score == 0) HG19_GENCODE_ANNOTATION_GENE_GTF;
compiles and runs correctly.

Whereas, the following statement:
DATA_SET_VAR = SELECT(region: score == '0') HG19_GENCODE_ANNOTATION_GENE_GTF;
compiles correctly, but then gives a run time error (due to score == '0' instead of score == 0).

It seams that the compiler does not check correctness of select statements against the type of region attributes described in the dataset schema; can this check be performed at compile time (and so avoid the run time error)?

**Comment by pp86** [comment]
It now checks the type of the predicate at compile times
