### ISSUE TITLE
Avoid default for GROUP() and EXTEND() 

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#73]
@pp86 
Currently default form EXTEND() and GROUP() are acceptable and generate in output a copy of the input dataset. Yet, we already have an operator to copy in output an input dataset, i.e., SELECT().
Make not possible compile EXTEND() and GROUP(), requiring for each of them at least a parameter for correct compiling. 

Also check that DG(N) accepts only non negative N values (as DGE(N) does)

**Comment by pp86** [comment]
Extend has been fixed. 

Please refer to issue #75 for group behaviour.
