### ISSUE TITLE
problems on JOIN (genometric predicate)

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/GMQL#74]
I am obtaining wrong results with this query

DATA_SET_VAR = SELECT() A;
DATA_SET_VAR2 = SELECT() B;
RES = JOIN(DISTANCE<0;output:LEFT_DISTINCT)  DATA_SET_VAR DATA_SET_VAR2;
MATERIALIZE RES INTO C;

Regardless of the output option

![image](https://user-images.githubusercontent.com/11488353/31114433-598d579e-a81e-11e7-9ef5-731fd6128e48.png)
Black is DATA_SET_VAR
Brown is DATA_SET_VAR2
Blue is RES

Why are not the two input regions on the right considered in the result?

@andreagulino

**Comment by akaitoua** [comment]
@andreagulino , This is a containing region. Did the last fix affected considering the containing region, Please check it out.

**Comment by andreagulino** [comment]
@sunbrn, do you have the samples in the figure?

**Comment by sunbrn** [comment]
[job_join_issue74_bernasconi_20171011_230336_mydsaJOIN_LEFTDIST.zip](https://github.com/DEIB-GECO/GMQL/files/1377172/job_join_issue74_bernasconi_20171011_230336_mydsaJOIN_LEFTDIST.zip)
[job_join_issue74_bernasconi_20171011_230336_mydsaJOIN_LEFTDIST_INPUT.zip](https://github.com/DEIB-GECO/GMQL/files/1377173/job_join_issue74_bernasconi_20171011_230336_mydsaJOIN_LEFTDIST_INPUT.zip)
[job_join_issue74_bernasconi_20171011_230336_mydsaJOIN_LEFTDIST_INPUT2.zip](https://github.com/DEIB-GECO/GMQL/files/1377174/job_join_issue74_bernasconi_20171011_230336_mydsaJOIN_LEFTDIST_INPUT2.zip)


Yes, I joined the ones with name ending with INPUT and INPUT2
with the statement:
RES = JOIN(DISTANCE<0;output:LEFT_DISTINCT)  DATA_SET_VAR DATA_SET_VAR2;

In the .zip ending with LEFTDIST you find the output

**Comment by sunbrn** [comment]
@andreagulino 
What is the situation at the moment? Please let me know when it is fixed

**Comment by andreagulino** [comment]
@akaitoua I didn't do any change to the Join implementation so far

**Comment by akaitoua** [comment]
The regions are distinct in each sample. The duplication is shown int he above figure because this is a result of two files. I fixed the problem of the containing region. Now you can use a negative distance to represent a containing region.
