### ISSUE TITLE
dataset renaming convert schema type from GTF to TAB

### ISSUE THREAD

**Issue by acanakoglu** [DEIB-GECO/GMQL#76]
When a GTF dataset is renamed, it lost its information about schema type and also coordinate_system. In general, it generates a new schema file which is not correct.

**Comment by acanakoglu** [comment]
Hi @akaitoua ,
"coordinate_system" is optional, and if it is not exists then import ds doesn't. Could you please correct it?

**Comment by marcomass** [comment]
@akaitoua 
Please give top priority to solve this issue since acanakoglu says that without solving it is not possible to update the system online and thus the testing and example development cannot be done; thanks.

**Comment by akaitoua** [comment]
@marcomass  solved.
