### ISSUE TITLE
Enable DEFAULT() option for semijoin/joinby/groupby conditions 

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/GMQL#77]
I have verified that:
- EXACT(<meta_attribute>) **works**
- FULLNAME(<meta_attribute>) **works**
- <meta_attribute> **works**
- DEFAULT(<meta_attribute>) **does not work**

Also this last option should be enabled.

@pp86

**Comment by marcomass** [comment]
@pp86 
The 4 options above applies on all the following operators:
- semijoin of SELECT
- joinby of DIFFERENCE, MAP, and JOIN 
- groupby of GROUP, MERGE, and COVER

**Comment by pp86** [comment]
What should DEFAULT do?

**Comment by sunbrn** [comment]
@pp86, the semantics of DEFAULT is the same of not specifying anything.

E.g., 
C = SELECT(semijoin: cell_type IN B) A;
must produce the same effect as
C = SELECT(semijoin: DEFAULT(cell_type) IN B) A;

**Comment by marcomass** [comment]
@pp86 
The syntax reported above by Anna is the one that you defined time ago, in which DEFAULT(<meta_attribute>) acts as <meta_attribute> alone.
You already implemented this behavior for some operators (I think merge, join, map; to be checked), but nor for others. Please make implementation consistent, implementing it for all operators where it should apply, or removing it from all operators (leaving for the same behavior only <meta_attribute>).

As well FULLNAME(<meta_attribute>) could be simplified into FULL(<meta_attribute>), similarly to EXACT(<meta_attribute>).

**Comment by pp86** [comment]
FULLNAME renamed to FULL.

Default is never used, please remove from the documentation if mentioned.
