### ISSUE TITLE
EXTEND problem with q1 aggregate function

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/GMQL#79]
DS1 = SELECT() DS0;
DS2 = EXTEND(q1Score AS q1(score)) DS1;
MATERIALIZE DS2 into DS_OUT;

The statement compiles correctly, but when I execute I get a DS_CREATION_FAILED error, which I attach.

[Untitled.txt](https://github.com/DEIB-GECO/GMQL/files/1394836/Untitled.txt)

Note that all other aggregate functions are instead working properly in EXTEND, including q2 and q3!

@OlgaGorlova @akaitoua

**Comment by OlgaGorlova** [comment]
Hi @sunbrn! Can you please provide me with the dataset that you used when the issue occurred? I could not reproduce the issue on the server.

**Comment by sunbrn** [comment]
Hi @OlgaGorlova 
I used this query:

DATA_SET_VAR = SELECT() dsCOMP;
RES = EXTEND(q1Score AS q1(score)) DATA_SET_VAR;
MATERIALIZE RES into EXTEND_ALL_withq1;

dsCOMP is the following:
[dsCOMP.zip](https://github.com/DEIB-GECO/GMQL/files/1430173/dsCOMP.zip)
