### ISSUE TITLE
Region selection based on coordinates

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#84]
@akaitoua @pp86 
Region selection based on coordinates currently is not possible; as a good alternative it is suggested to first copy coordinates on region attributes, and than filter regions according to such new attributes.
Yet, when chrom and strand coordinates are copied in a new region attribute, the new attribute is set as type double, thus preventing selection on this attribute based on usual chrom and strand values, which are string and char, respectively.
Furthermore, start/stop (or left/right, or end) coordinates are not recognized to be copied in a new region attribute.
Please make the above working.

As a testing example you can use the following query:
D = SELECT(cell == "Urothelia" AND ID == "40") HG19_ENCODE_NARROW;
D1 = PROJECT(region_update: chrom1 AS chr, strand1 AS strand, start1 AS start, stop1 AS stop) D;
D2 = SELECT(region: chrom1 == "chr1") D1;
D3 = SELECT(region: strand1 == "*") D2;
D4 = SELECT(region: start1 > 1000) D3;
D5 = SELECT(region: stop1 < 1000000) D4;
MATERIALIZE D5 into DATA;

**Comment by pp86** [comment]
I corrected the problem in the schema after copying CHR or STRAND.

The correct syntax for the CHR and STRAND selection is without the quotes.

**Comment by sunbrn** [comment]
@pp86 
For some reason this 
**D1 = PROJECT(region_update: chrom1 AS chr, strand1 AS strand, start1 AS start, stop1 AS stop) D;**
does not work 
(Message: Operator PROJECT at line 1: invalid syntax for parameter 'region_update'. String 'chrom1 as chr , strand1 as strand , start1 as start , stop1 as stop' not recognized.)
but this
**D1 = PROJECT(region_update: chrom1 AS chr, strand1 AS strand, sta1 AS start, sto1 AS stop) D;**
does work.

It doesn't like a new region attribute being called start.* or stop.* (regular expression syntax intended)

**Comment by OlgaGorlova** [comment]
@sunbrn @pp86 
I also found that it is not possible to update strand
**D1 = PROJECT(region_update: strand AS "*") D;**
I am not sure if it should be allowed, but it does not work. Instead of updating strand, it adds a new column with the **"*"** value.

**Comment by marcomass** [comment]
@OlgaGorlova @pp86 @akaitoua @sunbrn 
Thank you Olya to spot the problem. 
Yes, it must be possible to update strand and any coordinate (also chr, right, left). 
In fact one of the application example we defined long time ago regards ChIA-pet data, where there are pairs of regions: to accommodate such data in our model we defined to load the coordinates of one of the two regions in the region coordinartes of a region data tuple of our model, whereas the second paired region coordinates are loaded as additional attributes of the first region in the same tuple; then, we defined that, if it is needed to work on the second region, the first region coordinates can be copied in additional region attributes of the same tuple and the second region coordinates can be copied from the region attributes to the region coordinates of the same tuple. 
Thus, region coordinates should be updatable correctly. Please make this work.

**Comment by sunbrn** [comment]
It seems that what I pointed out has been fixed by the commit "Fix the problem of creating new fields name starting with..."
But what @OlgaGorlova has pointed out still holds. 
@pp86 can you please check if your commit "Makes possible to update value of CHR and STRAND"?

If I do 
D1 = PROJECT(region_update: chr AS "chr30", strand AS "\*") D;
instead of updating chr and strand, it adds a new columns with the "chr30" and "\*" values (the schema instead is correct).

**Comment by pp86** [comment]
@sunbrn, sorry, it looks like I messed it up with other commits.
It works now.

NB: if you do ' chr AS "" '  it is gonna fail in the executor because of the empty value.
