### ISSUE TITLE
JOIN DOWNSTREAM , WRONG OUTPUT

### ISSUE THREAD

**Issue by eirinistam** [DEIB-GECO/GMQL#86]
Running the following query Instead of having an empty result, we should get in output a single region, second one of D2:
D1 = SELECT(region: chr== chr4) dataset_179;
D2= SELECT(region: chr== chr4) dataset_280;
RES = JOIN(MD(1), DOWNSTREAM; output: RIGHT)D1 D2;
MATERIALIZE RES INTO OUT;
Attached the whole material.
[example_12.zip](https://github.com/DEIB-GECO/GMQL/files/1476268/example_12.zip)

**Comment by marcomass** [comment]
Unfortunately there are still issues with downstream + now upstream also provides wrong results; Eirini will load the testing examples, testing datasets and related screenshots.
@akaitoua if you need clarification about how it should work, please let me know so that we can talk through skype

**Comment by eirinistam** [comment]
Here are the testing examples and screenshot:
[join_12.zip](https://github.com/DEIB-GECO/GMQL/files/1521059/join_12.zip)
![picture1](https://user-images.githubusercontent.com/26028864/33476701-32ebf774-d683-11e7-9c2a-d2a17e53fee4.png)
In query above reported, with DOWNSTREAM, the output for MD(1), DOWNSTREAM predicate should be empty, whereas for DOWNSTREAM, MD(1) predicate only second region in second input sample should be in output (twice).
With UPSTREAM, the first and third regions of the second input samples should be in output.

**Comment by pp86** [comment]
Should have been fixed along with issue #92
