### ISSUE TITLE
Standardization of names in datasets created by API and web services

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#87]
Datasets created by web include a schema file named "schema.xml" and a subdirectory named "files".
Conversely, datasets created by API include a schema file named "test.xml" and a subdirectory named "exp".
The two output has to be standardized setting the names created by the API as the ones (more intuitive) created by the web.
This is due to avoid possible conflicts in pyGMQL / RGMQL which manage both files created (remotely) by web and file created locally by API

**Comment by lucananni93** [comment]
From the point of view of PyGMQL this is not a serious problem and, for the moment, I can handle this behavior from my side. If there are more serious issues, please address them before.

**Comment by marcomass** [comment]
This can be an issue in RGMQL (I'm glad it is not in pyGMQL ;-) )

**Comment by lucananni93** [comment]
I would propose to leave this as an enhancement for the moment since there are more important issues to solve.

**Comment by marcomass** [comment]
@akaitoua 
Could you please change the name of the schema file of a dataset generated by the API from "test.schema" to "schema.xml" and make the read dataset API reading such schema.xml file when using CustomParser?
This is affecting RGMQL usage: datasets created and downloaded trough web services cannot be read by API. 

Also, please standardize name of subdirectory, changing the name of the subdirectory generated by the API from "exp" to "files"

**Comment by acanakoglu** [comment]
The _exp_ folder will be changed into _files_ as discussed in the GitHub issue: https://github.com/DEIB-GECO/PyGMQL/issues/13

The name of the schema is a bit difficult because of the back-compatibility problem. The schema names should be changed for currently available DSs. I would resolve this as a later correction.

**Comment by marcomass** [comment]
Thanks @acanakoglu 
The issue of the schema file name is currently preventing the API from reading any dataset regardless where it was created, affecting particularly RGMQL.
Could this fix not delayed, making the API able to read with CustomParser schema file named schema.xml?

**Comment by marcomass** [comment]
@acanakoglu (cc. @Sim1Pall8a )
The issue is in the function setSchema() of the API for custom parser, which check if a XML .schema file exist; if not it generates error. It should be managed also the possibility to find a schema file named .xml instead.
Could you please do it?

**Comment by acanakoglu** [comment]
DONE
