### ISSUE TITLE
Removal of files *.crc and _SUCCESS from datasets created by API

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#88]
@akaitoua  @andreagulino 
Datasets created by API include files *.crc and file _SUCCESS, which appears meaningless and are not included in datasets created by web.
Please remove such files from datasets created by API.

**Comment by akaitoua** [comment]
I removed the _SUCCESS file, but i have no idea how to remove the .crc files since they are hidden.

**Comment by lucananni93** [comment]
This issue is currently handled by PyGMQL. Of course this should be handled by the scala backend but I think that for now it is fine to.keep it like that.

**Comment by marcomass** [comment]
Please make the scala backend handle this issue by to avoid that any application (PyGMQL, RGMQL, ...) has to handle it independently.
