### ISSUE TITLE
Project duplicate metadata attribute

### ISSUE THREAD

**Issue by eirinistam** [DEIB-GECO/GMQL#89]
Given the following query we expect the patient_age attribute to have a new value, instead, 
the result is 2 patient_age attributes with different values.
D= SELECT(region: chr == chr1) dataset_1;
RES = PROJECT(metadata_update: patient_age AS patient_age + 10) D;
MATERIALIZE RES INTO TAB;
enclosed the material

[project.zip](https://github.com/DEIB-GECO/GMQL/files/1501083/project.zip)

**Comment by akaitoua** [comment]
@marcomass, this error might be generated from the compiler. The implementation only performs the operation based on the indexes provided by the compiler.

**Comment by pp86** [comment]
compiler has nothing to do with that.
