### ISSUE TITLE
DIFFERENCE with exact option

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#9]
@akaitoua
Enable at the compiler level, as alternative to the difference of overlapping regions, also the difference of only exactly the same regions

Add a parameter in the Difference syntax that indicates this option (e.g. "exact: yes", o whatever else)

@Abdo by Pietro: now IRDifference takes a boolean default parameter for the EXACT option.

**Comment by akaitoua** [comment]
@marcomass, Implemented. You can check the changes with the new deployment. e42bc5a

**Comment by marcomass** [comment]
@akaitoua 
The option exact seems working fine, but I need to reopen this issue since the output dataset must include only metadata of the left input dataset, i.e., each output sample should have only the same metadata as the corresponding sample in the left input dataset. I reopen the issue.
You can use the following query as test:
test = SELECT() testDiff;
test_2 = PROJECT(region_update: length AS right-left) test;
MATERIALIZE test_2 INTO test_2;
mask = SELECT(region: length > 1000) test_2;
MATERIALIZE mask INTO mask;
test_filt_exact = DIFFERENCE(exact: true) test_2 mask;
test_filt = DIFFERENCE() test_2 mask;
MATERIALIZE test_filt_exact INTO test_filt_exact;
MATERIALIZE test_filt INTO test_filt;
[test.zip](https://github.com/DEIB-GECO/GMQL/files/1290973/test.zip)
