### ISSUE TITLE
ORDER wrong number output samples

### ISSUE THREAD

**Issue by eirinistam** [DEIB-GECO/GMQL#90]
Given the following query, we expect 2 samples as output but only one is returned.
D = SELECT(region: chr==chr1) dataset_1;
RES = ORDER( avg_score, ID DESC; meta_top: 2) D; 
MATERIALIZE RES INTO TAB;

Enclosed the material
[order.zip](https://github.com/DEIB-GECO/GMQL/files/1501114/order.zip)

**Comment by marcomass** [comment]
@eirinistam 
Can you check if this issue is solved?

**Comment by marcomass** [comment]
Solved
