### ISSUE TITLE
JOIN(on_attribute) wrong output results 

### ISSUE THREAD

**Issue by eirinistam** [DEIB-GECO/GMQL#91]
With the following query :
D1 = SELECT(region: chr == chr2) example_dataset_1;
D2 = SELECT(region: chr == chr2) example_dataset_2;
RES= JOIN(DL(0); on_attributes: score; output:INT ) D1 D2;
MATERIALIZE RES INTO join_10;
Instead of an empty dataset, returned intersected regions with score 0.0

I enclose the material:
[join_10.zip](https://github.com/DEIB-GECO/GMQL/files/1518330/join_10.zip)

**Comment by akaitoua** [comment]
@eirinistam, you said "Instead of an empty dataset, returned intersected regions with score 0.0" but, This is how it is supposed to work. @marcomass, correct me if i am wrong.

**Comment by marcomass** [comment]
@akaitoua The query in the example include the option "on_attributes: score;" which selects first the regions in the joined samples that have the same value of the attribute score (provided that both the joined datasets have the region attribute score). In the example case, none of the regions in any of the samples in the second dataset has the same value for the attribute score of the regions in the sample in the first (anchor) dataset; thus, the result must be empty. 
The same should occur if any of the two joined datasets has the attribute score in the schema (please check also this case.
