### ISSUE TITLE
Schema attribute type after NULL() or META()

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#93]
When executing a PROJECT that sets as NULL(TYPE) an existing region attribute, the values of the attribute are correctly set to null, but its type in the output schema is not changed to TYPE.
Please use the following query to test the peak attribute type
D = SELECT(region: chr == chr1) Example_Dataset_1;
RES = PROJECT(region_update: qvalue AS NULL(DOUBLE), peak AS NULL(INTEGER), other AS NULL(DOUBLE)) D;
MATERIALIZE RES INTO RESULT_DS;

**Comment by marcomass** [comment]
Unfortunately this is not solved. 
Using the testing query above, still in the output dataset RES the region attribute peak remains DOUBLE (as it was in input) despite in the query it is set to INTEGER.
Please fix this.

**Comment by pp86** [comment]
@marcomass @akaitoua @andreagulino 

It looks like there is a problem with the system, not with the compiler. Indeed the compiler produces the right schema. 
Also, in the HDFS we have the right schema, but in the local FS the INTEGER is changed into a DOUBLE

**Comment by marcomass** [comment]
@pp86 @OlgaGorlova @akaitoua 
Same applies also when a new region attribute is created using META()
Please fix and test using the following query:
D = SELECT() Example_Dataset_1;
RES = PROJECT(region_update: sampleID AS META(ID, INTEGER ), score AS META(avg_score, DOUBLE), cell AS META(cell, STRING)) D;
MATERIALIZE RES INTO project_10;
[dsets_15-12-17.zip](https://github.com/DEIB-GECO/GMQL/files/1584963/dsets_15-12-17.zip)

**Comment by pp86** [comment]
Same problem here; compiler works, there is a problem when the schema is copied.

I have no idea where to look for it.

**Comment by marcomass** [comment]
@akaitoua can you please deal with this issue?

**Comment by akaitoua** [comment]
@marcomass, I found the problem source and fix it. I do not have the ability to test the change. I expect it to work now. Please let me know if it did not.

**Comment by marcomass** [comment]
In output dataset schema file the issue is now fixed.
Yet in the web interface Schema section, schema attributes of type INTEGER are always reported as of type DOUBLE. I opened for this a new GMQL web issue (#61) [https://github.com/DEIB-GECO/GMQL-WEB/issues/61](url)
