### ISSUE TITLE
Avoid "." in dataset / file name

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#95]
Avoid using character "." in materialized dataset file name, e.g.:
MATERIALIZE RES INTO cover_ex.2;

**Comment by acanakoglu** [comment]
it is not possible to resolve in the compiler level, this check was added to execution process.

**Comment by marcomass** [comment]
@acanakoglu 
The fix is fine, but please add in the error message the information to the user why the dataset name is not valid, e.g. adding at the end of the message "Please, avoid using ".""

**Comment by lucananni93** [comment]
This is also important for the APIs. Does this fix affect them automatically or should I add the check at the API level?

**Comment by marcomass** [comment]
@acanakoglu ?

**Comment by marcomass** [comment]
@acanakoglu 
Does this require any change in RGMQL / pyGMQL?
