### ISSUE TITLE
PROJECT()

### ISSUE THREAD

**Issue by marcomass** [DEIB-GECO/GMQL#96]
The default condition PROJECT() should generate the output dataset with only coordinates and no other region attributes, whereas currently it copies in output the same dataset as in input. 
Please use the following query to test:
D = SELECT() Example_Dataset_1;
RES0 = PROJECT() D;
MATERIALIZE RES0 INTO RES0;

**Comment by marcomass** [comment]
Unfortunately this is not fixed.
Output schema still contains all input attributes (6 in the example, i.e. the 4 required ones + 2 that should be removed).
Output samples contain values of only the required 4 attributes, but also an additional empty column attribute (which shouldn't, and it is not consistent with the remained schema that wrongly include 6 attributes).
Maybe @acanakoglu can help?

**Comment by marcomass** [comment]
Schema now is fixed. But schema file in the materialized dataset includes an empty line before the tag line </gmqlSchema>, which shouldn't be.

Furthermore, still output samples contain an additional empty column attribute (besides the required 4 ones), which shouldn't be according to the schema and could create problems in further processing. 
Please remove them.

**Comment by acanakoglu** [comment]
The tab character problem is related to materialization of generated DSs with only 4 standard columns, in other words without any extra columns. 
The mentioned schema is not an issue, as known, the such empty lines doesn't effect the definition of the XML.
